### ISSUE TITLE
offset_urg_tfによって提供される設定ファイルについて

### ISSUE THREAD

**Issue by YusakuSakamoto** [CIR-KIT/third_robot_2dnav#1]
このthird_robot_2dnavのパッケージをビルドするに当たり、offset_urg_tfによって提供される設定ファイルが見つかりませんというエラーが出ました。申し訳ありませんが対処方法をご教授いただけませんでしょうか。
@AriYu

**Comment by AriYu** [comment]
@YusakuSakamoto エラーメッセージを貼り付けてください。

**Comment by YusakuSakamoto** [comment]
エラーメッセージ
---------------------------------------------------------------------------------------------------------------
-- +++ processing catkin package: 'third_robot_2dnav'
-- ==> add_subdirectory(third_robot_2dnav)
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:75 (find_package):
  Could not find a package configuration file provided by "offset_urg_tf"
  with any of the following names:

    offset_urg_tfConfig.cmake
    offset_urg_tf-config.cmake

  Add the installation prefix of "offset_urg_tf" to CMAKE_PREFIX_PATH or set
  "offset_urg_tf_DIR" to a directory containing one of the above files.  If
  "offset_urg_tf" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  third_robot_2dnav/CMakeLists.txt:7 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/sakamoto/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/sakamoto/catkin_ws/build/CMakeFiles/CMakeError.log".

以上です。
よろしくお願いします。

**Comment by RyodoTanaka** [comment]
@YusakuSakamoto 
自作した`offset_urg_tf`が`<catkin_ws>/src`ディレクトリに無いため、このようなエラーが出ると考えられます。（尚、`<catkin_ws>`は、catkinのワークスペースのパスを指します。自分で読み替えて下さい。）
`<catkin_ws>/src`へ移動し、以下のコマンドで`offset_urg_tf`をcloneして下さい。

```bash
git clone https://github.com/CIR-KIT/offset_urg_tf.git
```

また、`third_robot_nav_goals`もcloneしていないと思われますので、これも合わせて行うようにして下さい。

```bash
git clone https://github.com/CIR-KIT/third_robot_nav_goals.git
```

**Comment by RyodoTanaka** [comment]
@YusakuSakamoto 
先ほど投稿したもので、cloneを行っていますが、それはHTTPSを利用したcloneです。もし、SSHの設定を行っているなら、以下のコマンドでもcloneできます。もちろん、`<catkin_ws>/src`でcloneするよう、おねがいします。

- `offset_urg_tf`
```bash
git clone git@github.com:CIR-KIT/offset_urg_tf.git
```

- `third_robot_nav_goals`
```bash
git clone git@github.com:CIR-KIT/third_robot_nav_goals.git
```

**Comment by YusakuSakamoto** [comment]
@RyodoTanaka 
ありがとうございます。コンパイルが無事に通ったことを確認できました。
また何かありましたらまたissueで質問させて頂きます。
夜分遅く失礼しました。

**Comment by RyodoTanaka** [comment]
@YusakuSakamoto 
うまくいってよかった ! !
