### ISSUE TITLE
urg_filterの件

### ISSUE THREAD

**Issue by YusakuSakamoto** [CIR-KIT/third_robot_2dnav#2]
move_base.launch内のurg_filterについてですが、先日のInfinity Filterというものでしょうか。
そのまま検索しても引っかからないので、どのようにすればよいですか。
よろしくお願いします。

@RyodoTanaka 
@AriYu

**Comment by AriYu** [comment]
@YusakuSakamoto 
`urg_filter`リポジトリを作成しました。
https://github.com/CIR-KIT/urg_filter

`<catkin_ws>/src`にcloneしてください。

**Comment by YusakuSakamoto** [comment]
了解しました。
